sudo: false  
dist: trusty  
language: node_js  
node_js:  
 - "7"

addons:
  chrome: stable
before_script:
  - cd gulp
  - npm install -g karma
  - npm install -g gulp
  - npm install
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
script: gulp travis-test
after_success: 
  - gulp commitDevBuild
  - gulp coveralls